# Consistent Bayes: Some Motivating Examples
---

Copyright 2017-2018 Michael Pilosov


### Import Libraries
_tested on 3.6 01/23/18_

In [93]:
# Mathematics and Plotting
from HelperFuns import * # pyplot wrapper functions useful for visualizations, numpy, scipy, etc.
%matplotlib inline
plt.rcParams.update({'font.size': 14})
plt.rcParams['figure.figsize'] = 10, 5
from cbayes import sample, solve
# Interactivity
from ipywidgets import *

---

Some introductory text goes here.   
Define $\Lambda$, $\mathcal{D}$.


--- 

## Sample from $\Lambda$
_Here we implement uniform random priors on the unit hypercube, but you can load in any set of samples in its place._

In [2]:
input_dim = 2 # Specify input space dimension (n)
num_samples = int(1E4) # number of input samples (N)
s_set = sample.sample_set(size=(num_samples, input_dim))
s_set.set_dist('uniform')
s_set.generate_samples()
lam = s_set.samples

---
## Define Parameter to Observables (PtO) Map
_ Choose from one of the following example options, feel free to add your own _ 

$O_1(\lambda) = \sum_{i=1}^n \lambda_i$  

$O_2(\lambda) = \alpha \, \lambda_1$, $\alpha = 2$  

$O_3(\lambda) = \lbrace \lambda_0 - \lambda_1, \; \;\lambda_1\rbrace$ 

$O_4(\lambda) = \lbrace \lambda_0+\lambda_1, \; \lambda_2, \; \lambda_3-\lambda_4 \rbrace$  

In [3]:
def fun1(lam): # sum all params
    return np.sum(lam,axis=1)

def fun2(lam): # pull param, scale it.
    return np.array([ 2*lam[:,0] ]).transpose()

def fun3(lam): # pull two params, linear combination.
    return np.array([ lam[:,0] - lam[:,1], lam[:,1] ]).transpose()

def fun4(lam): # pull three sets of params, linear combinations thereof.
    return np.array([ lam[:,0]+lam[:,1], lam[:,2], lam[:,3]-lam[:,4] ]).transpose()

In [86]:
PtO_fun_choice = 1

if PtO_fun_choice == 1:
    PtO_fun = fun1
elif PtO_fun_choice == 2:
    PtO_fun = fun2
elif PtO_fun_choice == 3:
    PtO_fun = fun3
elif PtO_fun_choice == 4:
    PtO_fun = fun4
else:
    raise( ValueError('Specify Proper PtO choice!') )

---
## Compute Data Space $O(\Lambda) = \mathcal{D}$ 

Format: `(n_dims, n_samples)`  
_Optional_: Specify subset of PtO map's components to use for inversion using the variable `sub_indices` 

In [87]:
p_set = sample.map_samples_and_create_problem(s_set, PtO_fun)
D_full = p_set.output.samples

sub_indices = None
if sub_indices is not None:
    D = D_full[:,sub_indices]
else:
    D = D_full
    type(np.sum(lam, axis=1))
# this is how we handle exceptions:
try:
    output_dim = D.shape[1]
except IndexError:
    output_dim = 1
print('dimensions :  lambda = '+str(lam.shape)+'   D = '+str(D.shape)+'   D_full = '+str(D_full.shape) )

dimensions :  lambda = (10000, 2)   D = (10000,)   D_full = (10000,)


## Compute Push-Forward of the Prior $P_{O(\Lambda)}$
_ ... i.e. Visualize the Data Space_

In [88]:
# Interactive Marginal Visualization
p_set.compute_pushforward_dist()
pf_dens = p_set.pushforward_dist

# Can plot "slices" of densities to observe differences between posterior and prior, but not that useful

a, b = -0.25, 2.125 # linspace parameters for plotting
plot_grid = np.linspace(a, b, 100)

widgets.interact(view_est_dens, x = fixed(plot_grid), 
         estimated_dens = fixed(pf_dens), 
         lab = fixed('KDE data'), title=fixed('Pushforward of Prior'),
         viewdim=(0, output_dim-1, 1) )
plt.show()

interactive(children=(IntSlider(value=0, description='viewdim', max=0), Output()), _dom_classes=('widget-interact',))

## Define Observed Probability Measure $P_\mathcal{D}$

In [92]:
# We will use multivariate normals because of their common scipy.stats call syntaxes.
var_const = 0.25 # constant variance for simplicity
cov_matrix = var_const*np.eye(output_dim) # if you want non-constant, use code snippet below
# cov_matrix = np.diag( np.round(np.random.rand(1,output_dim),2)[0] ) # random independent covariances
means = np.zeros(output_dim) + 0.875 # observed density center (maximum)
# obs_dens = sstats.multivariate_normal(mean = means, cov = cov_matrix )
p_set.set_observed_dist('uniform', means, var_const)
obs_dens = p_set.observed_dist

# # For the 1-dimensional case, we can utilize the uniform density given below
# # TODO: generalize uniform box to n-dimensional case
# uni_max = 0.5
# obs_dens = sstats.uniform(0,uni_max) # 1D only

# a, b = 0, 1 # linspace parameters for plotting
plot_grid = np.linspace(a, b, 100)

widgets.interact(view_analytical_dens, x = fixed(plot_grid), 
         analytical_dens = fixed(obs_dens), 
         lab = fixed('KDE data'), title=fixed('Observed $P_\mathcal{D}$'),
         viewdim=(0, output_dim-1, 1) )
plt.show()

interactive(children=(IntSlider(value=0, description='viewdim', max=0), Output()), _dom_classes=('widget-interact',))

---

At this point we have performed the computations we need to. We have evaluated the input points through our map and performed a KDE on them. It would be useful at this point to save this object and/or its evaluation at every point in the data space for later re-use. Doing so here would be an appropriate place. 

--- 

## Accept/Reject Sampling of Posterior

Since we have already used the samples in our prior to compute the pushforward density, we can re-use these with an accept/reject algorithm to get a set of samples generated from the posterior according to the solution of the stochastic inverse problem as outlined in the Consistent Bayes formulation. 

In [81]:
accept_inds = []
# the transpose below is how analytical densities take their arguments. KDE objects do not require transpose.
r = np.divide(obs_dens.pdf(D), pf_dens.pdf(D)) # vector of ratios evaluated at all the O(lambda)'s
M = np.max(r)
eta_r = r/M

In [82]:
eta_r

array([[6.94570443e-12, 1.59037404e-05, 5.01852086e-13, ...,
        1.85135436e-04, 2.01437325e-10, 2.58483722e-14],
       [6.77755721e-12, 1.55187298e-05, 4.89702846e-13, ...,
        1.80653528e-04, 1.96560768e-10, 2.52226140e-14],
       [6.72791718e-12, 1.54050679e-05, 4.86116175e-13, ...,
        1.79330390e-04, 1.95121122e-10, 2.50378791e-14],
       ...,
       [8.54294312e-12, 1.95609748e-05, 6.17258316e-13, ...,
        2.27709301e-04, 2.47759982e-10, 3.17924806e-14],
       [6.72842170e-12, 1.54062231e-05, 4.86152628e-13, ...,
        1.79343838e-04, 1.95135754e-10, 2.50397566e-14],
       [6.73845041e-12, 1.54291861e-05, 4.86877239e-13, ...,
        1.79611150e-04, 1.95426603e-10, 2.50770784e-14]])

In [83]:
r.shape
p_set.set_observed_dist('normal', means, var_const)
p_set.set_ratio()
###
r = p_set.ratio
M = np.max(r)
eta_r = r/M

In [77]:
accept_inds = [i for i in range(num_samples) if eta_r[i] > np.random.uniform(0,1) ]
# lam_accept = np.array([lam[accept_inds, i] for i in range(input_dim)]).reshape((len(accept_inds),input_dim))
lam_accept = lam[accept_inds,:]
num_accept = len(accept_inds)
print('Number accepted: %d = %2.2f%%'%(num_accept, 100*np.float(num_accept)/num_samples))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
p_set.set_ratio()
p_set.ratio
p_set.ratio.shape

In [120]:
p_set.pushforward_dist.pdf(D).reshape(10000)

array([0.72661254, 0.84529299, 0.89972666, ..., 0.29624622, 0.76661057,
       0.91746067])

In [116]:
np.divide(p_set.observed_dist.pdf(D),p_set.pushforward_dist.pdf(D).transpose())

array([[0.        , 0.        , 4.44579467, ..., 0.        , 0.        ,
        4.3598599 ]])

In [99]:
solve.problem(p_set)

In [104]:
accept_inds = p_set.accept_inds
num_accept = len(accept_inds)
print('Number accepted: %d = %2.2f%%'%(num_accept, 100*np.float(num_accept)/num_samples))

Number accepted: 1422248 = 14222.48%


### Visualize Accept/Reject Samples

In [103]:
interact(pltaccept, lam = fixed(lam), inds = fixed(accept_inds), 
         N = (1, num_accept+1, 10), eta_r = fixed(eta_r), 
         i = (0, input_dim-1, 1), j = (0, input_dim-1, 1))
# You will visualize the accepted samples in a subset of size N of the input samples
plt.show()

interactive(children=(IntSlider(value=711121, description='N', max=1422249, min=1, step=10), IntSlider(value=0, description='i', max=1), IntSlider(value=1, description='j', max=1), Output()), _dom_classes=('widget-interact',))

---
## Visualize Posterior Density

In [13]:
prior_dens_kde = gkde(lam)
post_dens_kde = gkde(lam_accept)

a, b = 0, 1 # linspace parameters for plotting
plot_grid = np.linspace(a, b, 100)

# Can plot "slices" of densities to observe differences between posterior and prior, but not that useful
interact(compare_est_input_dens, x = fixed(plot_grid), 
         estimated_dens1 = fixed(prior_dens_kde), estimated_dens2 = fixed(post_dens_kde), 
         lab_1 = fixed('KDE prior'), lab_2 = fixed('KDE post'), title=fixed(''),
         viewdim=(0, input_dim-1, 1))
plt.show()

NameError: name 'gkde' is not defined

## Visualize Quality of Solution 
_We compare the push-forward of the posterior using accepted samples against the observed density_

In [ ]:
push_post_dens_kde = gkde([D[k][accept_inds] for k in range(output_dim)])

a, b = 0, 1 # linspace parameters for plotting
plot_grid = np.linspace(a, b, 100)


# diagonal crossection view
interact(compare_output_dens, x = fixed(plot_grid), 
         analytical_dens = fixed(obs_dens), estimated_dens = fixed(push_post_dens_kde), 
         lab_1 = fixed('observed'), lab_2 = fixed('KDE push'), title = fixed('Marginal - Observed v. PF'),
         viewdim = (0, output_dim-1, 1))
plt.show()